### ISSUE TITLE
checkpoint_[1, 1]_33_0.002_89.162.pth.tar

### ISSUE THREAD

**Issue by eugene123tw** [kaiwang960112/Challenge-condition-FER-dataset#10]
Thanks for answering my last question. I really like your work. Could you also share the best trained model on Google Drive/OneDrive? I have been trying for hours and I still couldn't download it from baidu for some reason.

**Comment by kaiwang960112** [comment]
These days are the deadline of the CVPR. Could you give me more time to update the model that you need? Thanks a lot. Another method is you can download from Google Driver, I remember I have uploaded all the models on Google Driver.

**Comment by eugene123tw** [comment]
> These days are the deadline of the CVPR. Could you give me more time to update the model that you need? Thanks a lot. Another method is you can download from Google Driver, I remember I have uploaded all the models on Google Driver.

Thank you! However I could only see `ijba_res18_naive.pth` from here (https://drive.google.com/drive/folders/1dpDntw-2jLCNgjZ20W9aLg8a6DEEo7gX).

**Comment by darshangera** [comment]
Hi,
Can you please clarify:
Is ijba_res18_naive.pth model finetuned on FER datasets or just pre-trained only on FR task only? I wish to used pretrained model for a new model. Can you please point me to where to get resnet-18 pretrained on MSceleb?
Thanks
