### ISSUE TITLE
some questions about landmark-based cropping using a radius r

### ISSUE THREAD

**Issue by juneweng** [kaiwang960112/Challenge-condition-FER-dataset#2]
It is a great work!

In your paper, Setting the radius as 0.4 of the side of image for landmark-based cropping.I just find the max and min of xy coordinates, then add pad.But I don't know how to crop using a radius.Can you give a example? Thanks a lot!

**Comment by kaiwang960112** [comment]
For example, if you have the xy coordinates of the left eye, the radius is 0.4 of the face size. The following steps can crop the region:
1. Randomly choose a point at the top-left of the left eye and then expand to find a down-right point. 
2. Then you can get a box, the box size is about 0.8 of the face size.

I hope my answer can help you.

**Comment by juneweng** [comment]
Thank you for your early reply!

It can be interpreted as the crop image is 0.8 of the original image or not? In addition, I am wondering the difference between dlib and MTCNN in landmark crop. Which one is more appropriate?

Thank you in advance!

**Comment by kaiwang960112** [comment]
It is a case by case problem, you can do some experiments.

**Comment by juneweng** [comment]
Ok, thank you~
