### ISSUE TITLE
Pretrained model on MSceleb

### ISSUE THREAD

**Issue by darshangera** [kaiwang960112/Challenge-condition-FER-dataset#20]
Hi,
Can you please clarify:
Is ijba_res18_naive.pth model finetuned on FER datasets or just pre-trained only on FR task only? I wish to used pretrained model for a new model. Can you please point me to where to get resnet-18 pretrained on MSceleb?
Thanks

**Comment by onwaiers** [comment]
同问，请问作者在哪得到resnet18在msceleb的预训练模型的？还是自己训练的，能否提供一下链接之类的

**Comment by kaiwang960112** [comment]
这个已经提供了。发自我的华为手机-------- 原始邮件 --------发件人： onwaiers <notifications@github.com>日期： 2020年5月9日周六 下午2:36收件人： kaiwang960112/Challenge-condition-FER-dataset <Challenge-condition-FER-dataset@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： Re: [kaiwang960112/Challenge-condition-FER-dataset] Pretrained model on MSceleb (#20)

同问，请问作者在哪得到resnet18在msceleb的预训练模型的？还是自己训练的，能否提供一下链接之类的

**Comment by kaiwang960112** [comment]
ijba_res18_naive.pth is the pretrained model on ms1m。thank you-------- 原始邮件 --------发件人： Darshan Gera <notifications@github.com>日期： 2020年5月5日周二 中午12:56收件人： kaiwang960112/Challenge-condition-FER-dataset <Challenge-condition-FER-dataset@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [kaiwang960112/Challenge-condition-FER-dataset] Pretrained model on MSceleb (#20)
Hi,
Can you please clarify:
Is ijba_res18_naive.pth model finetuned on FER datasets or just pre-trained only on FR task only? I wish to used pretrained model for a new model. Can you please point me to where to get resnet-18 pretrained on MSceleb?
Thanks

**Comment by onwaiers** [comment]
> 这个已经提供了。发自我的华为手机-------- 原始邮件 --------发件人： onwaiers <notifications@github.com>日期： 2020年5月9日周六 下午2:36收件人： kaiwang960112/Challenge-condition-FER-dataset <Challenge-condition-FER-dataset@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主 题： Re: [kaiwang960112/Challenge-condition-FER-dataset] Pretrained model on MSceleb (#20) 同问，请问作者在哪得到resnet18在msceleb的预训练模型的？还是自己训练的，能否提供一下链接之类的 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

好的，明白了，十分感谢。

**Comment by darshangera** [comment]
Thank you so much. I got the model.

**Comment by DUT-MZY** [comment]
作者您好，我也需要msceleb的预训练模型，请问能否发我一份1148630707@qq.com,感激不尽！
