### ISSUE TITLE
why target = target_first?

### ISSUE THREAD

**Issue by YoungTaoD** [kaiwang960112/Challenge-condition-FER-dataset#34]
您好，我读了您的论文，并尝试运行您提供的代码，我有两个问题（我用的是FER的code）
1. 是必须所有种类的图片格式差别不能太大吗？我发现差别超过batch的话，就会报错
2. train_aatention_loss_rank.py 240行附近为什么target赋值为target_first?

**Comment by kaiwang960112** [comment]
已经回复 请close

**Comment by YoungTaoD** [comment]
好的，谢谢解答呀，圣诞快乐！

**Comment by kaiwang960112** [comment]
Merry Christmas-------- 原始邮件 --------发件人： dyt0414 <notifications@github.com>日期： 2020年12月24日周四 下午1:09收件人： kaiwang960112/Challenge-condition-FER-dataset <Challenge-condition-FER-dataset@noreply.github.com>抄送： "Kai Wang (Victor Kai)" <kai.wang960112@gmail.com>, Comment <comment@noreply.github.com>主    题： Re: [kaiwang960112/Challenge-condition-FER-dataset] why target = target_first? (#34)

好的，谢谢解答呀，圣诞快乐！
