### ISSUE TITLE
性能对比

### ISSUE THREAD

**Issue by wang21jun** [kaiwang960112/Challenge-condition-FER-dataset#4]
在TABLE VII中你将你们的算法和[44], [58]对比，据我所知[44]中report的是8个表情的平均准确率，[58]中为了和raf-db融合去除了表情contempt，report的是7个基本表情的平均准确率。另外[44]和[58]均未在人脸数据集上pretrian，这对表情结果识别影响不小。想咨询两个问题：
（1）你的59.5是8个表情的平均准确率还是7个表情的平均准确率？即有无包含contempt表情。
（2）你的59.5是否是在pretrain的人脸识别模型上训练而来？
多谢！

**Comment by kaiwang960112** [comment]
您好，这个问题问的特别好，我们在做对比实验的时候也认真读了其他作者的文章，58那篇是山世光老师组里的文章，我们在对比时候问过他们那边的同学，那个应该不是平均准确率，就是样本准确率。实际上，你可能误解了，因为affectnet的测试数据集每一类数目都是一样的（都是五百个）。我们这里的结果是八类的结果。
我们的59.5结果是在人脸数据集上预训练过的。

**Comment by wang21jun** [comment]
每一类数目都是一样的情况下，平均准确率和样本总体准确率是一样的，我的意思是他那个是7*500=3500张图片的准确率，你们的是8*500=4000张图片的准确率，个人感觉不太有可比性，分母不一样。

**Comment by kaiwang960112** [comment]
8500？我不太明白你的意思，要不我们微信交流，kaiwang-siat-2017
