### ISSUE TITLE
About "ferplus/pose_test/test_txt/"

### ISSUE THREAD

**Issue by PeiwenSun2000** [kaiwang960112/Challenge-condition-FER-dataset#44]
您好，感谢您开源代码，但是在复现过程中，我发现您并没有提供在test_rank_loss_attention.py 中的 "ferplus/pose_test/test_txt/"文件夹，此外，您在另外一个issue中说已经提供了，是您忘记上传了吗？

此外，您当前pytorch中部分代码已经在2020年以来的pytorch版本中弃用了。如果您能提供上面那个文件夹使我完成复现的话，我同样也希望可以为这个repo做出贡献，也希望commit一个新版本的代码，外加简单的image crop。期待您的回复~

**Comment by PeiwenSun2000** [comment]
如果您不方便提供，描述下test_txt/中txt的结构或者生成方式也可以，期待您的回复

**Comment by kaiwang960112** [comment]
没有什么不方便提供了，也早就提供了：在jianfei_occlusion_list.txt；pose_30_ferplus_list.txt；pose_45_ferplus_list.txt。这里面给了文件名字和label，然后你测试的时候就是每张图切六张放到以文件名命名的dir下。https://github.com/kaiwang960112/Challenge-condition-FER-dataset/tree/master/FERplus_dir 上述文件在这个网址下。

**Comment by kaiwang960112** [comment]
test_txt,是文件夹名字 然后空格 然后图片crop数目，然后空格 然后label，然后\n

**Comment by PeiwenSun2000** [comment]
好的好的，非常感谢您的回复~~
