### ISSUE TITLE
您好，我在load您开源的模型文件时遇到了一些问题，希望得到您的解答，谢谢

### ISSUE THREAD

**Issue by loganzhang1** [kaiwang960112/Challenge-condition-FER-dataset#45]
您好，感谢您在百忙之中查看我的issue。我在load您开源的模型时了一些问题，load模型的代码和出现的错误信息见下：
代码：
`all_data=torch.load('../../ijba_res18_naive.pth')

model=resnet18(end2end=False)

model.load_state_dict(all_data['state_dict'])

print('model',model)`

错误信息：
Missing key(s) in state_dict: "conv1.weight", "bn1.weight", "bn1.bias",......
        Unexpected key(s) in state_dict: "module.conv1.weight", "module.bn1.weight", "module.bn1.bias", ....

希望得到您的解答，谢谢。

**Comment by kaiwang960112** [comment]
这个我回答过了，需要把key加上个“module”或者去除

发自我的iPhone

**Comment by loganzhang1** [comment]
好的，谢谢您
