### ISSUE TITLE
occluded affectnet txt file dataset format

### ISSUE THREAD

**Issue by isack-ml** [kaiwang960112/Challenge-condition-FER-dataset#48]
I read your paper with great interest. 
thank you.

And I want to use the dataset you deployed, but I don't know how to use Affect-net with occlusion. 

The affect-net I downloaded is composed of affectnet/val/emotion number/images number, and your occluded affecnet txt file is affectnet/val/emotion number/bc9ad400db82eca1882b11c9603348fb3e92f5b0d67391ac22a1bc79/. The last part(images name) seems to be different from the format of the published dataset. 

How should I convert files name and use it?

It would be of great help if you could tell me how to use it.

**Comment by kaiwang960112** [comment]
The name after emotion name is unique. You can use it to find which image is occluded.发自我的 iPhone在 2023年2月13日，12:57，Lee Isack ***@***.***> 写道：﻿
I read your paper with great interest.
thank you.
And I want to use the dataset you deployed, but I don't know how to use Affect-net with occlusion.
The affect-net I downloaded is composed of affectnet/val/emotion number/images number, and your occluded affecnet txt file is affectnet/val/emotion number/bc9ad400db82eca1882b11c9603348fb3e92f5b0d67391ac22a1bc79/. The last part(images name) seems to be different from the format of the published dataset.
How should I convert files name and use it?
It would be of great help if you could tell me how to use it.

**Comment by isack-ml** [comment]
Thank you to your reply but i don't extract these occluded affectnet image. Can you share occluded affect net dataset for test? I don't understand your txt file's format 😭

**Comment by isack-ml** [comment]
yout txt file like this. I knew it.
![image](https://user-images.githubusercontent.com/52061393/218926806-a14f4306-3663-4386-84e1-82bdb60006a3.png)
But here's what I have. I was download it from official Affect-Net 
![image](https://user-images.githubusercontent.com/52061393/218927590-79abdd59-0cd8-4161-85db-a054f4122cf0.png)

As shown in the second image, my data also consists of a unique name, but the name format of each image is completely different from that of the txt file you shared.

**Comment by kaiwang960112** [comment]
maybe they has update the version of dataset

Lee Isack ***@***.***>于2023年2月15日 周三12:17写道：

**Comment by isack-ml** [comment]
Thank you

**Comment by MyungBeomHer** [comment]
Hello, I encounter this same problem. my affecnet datas file name is 0.jpg. which version has bc9ad400db82eca1882b11c9603348fb3e92f5b0d67391ac22a1bc79 in AffectNet? or how to get this version AffectNet data?

**Comment by kaiwang960112** [comment]
That is because of the upgrade of AffectNet. In 2017 and before, the name
is a very long string. JPG.

HMB ***@***.***>于2024年7月26日 周五21:21写道：

**Comment by MyungBeomHer** [comment]
Thank you for your very quick response. So if I request the 2017 version on the AffectNet homepage, will I get the corresponding occlusion list.txt file?

**Comment by kaiwang960112** [comment]
I think we can ask them to provide the txt and the h5 value of each image,
so we may get the mapping.

HMB ***@***.***>于2024年7月26日 周五21:41写道：

**Comment by MyungBeomHer** [comment]
Thank you so much, I'm so grateful for your kindness.

**Comment by kaiwang960112** [comment]
Maybe we can try.

HMB ***@***.***>于2024年7月26日 周五21:49写道：
