### ISSUE TITLE
缺少val_part_attention 这个文件

### ISSUE THREAD

**Issue by XiaoWang98** [kaiwang960112/Challenge-condition-FER-dataset#7]
作者你好,我在test_rank_loss里发现要import这个文件,能放出来一份val_part_attention 这个文件吗?多谢

**Comment by kaiwang960112** [comment]
好的，这两天放一下，哈哈哈发自我的华为手机-------- 原始邮件 --------发件人： 小王同学 <notifications@github.com>日期： 2019年10月24日周四 上午10:58收件人： kaiwang960112/Challenge-condition-FER-dataset <Challenge-condition-FER-dataset@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [kaiwang960112/Challenge-condition-FER-dataset] 缺少val_part_attention 这个文件 (#7)作者你好,我在test_rank_loss里发现要import这个文件,能放出来一份val_part_attention 这个文件吗?多谢

**Comment by XiaoWang98** [comment]
好的,多谢,另外在test文件里还有一个"/media/sdc/kwang/ferplus/pose_test/val_ferplus_mn.txt"这个能给一份吗?想看看这个txt里面的格式.

**Comment by kaiwang960112** [comment]
已经上传，谢谢关注我们的工作。

**Comment by YeeHoran** [comment]
Dear Kai Wang, 

There's only 'val_part_attention_sample.py' under the FERplus folder, but without 'val_part_attention.py'. Could you upload it, please? Or, is it possible that they are the same one, and the latter one could be replaced by the former one?

I am looking forward to your reply!

Thank you!
