### ISSUE TITLE
FER+ datasets

### ISSUE THREAD

**Issue by eugene123tw** [kaiwang960112/Challenge-condition-FER-dataset#9]
As far as I know FER+ provides images not videos. That being said, I don't quite understand why each face is represented as video in `part_attention_sample.py`. I'm gussing, If fixed position cropping is used, does this mean `video_path`  contains 6 images with different part + original image? Or how do you get the videos and extract frames?

```
img_path_first = video_path+'/'+img_lists[0]
img_path_second = video_path + '/'+img_lists[1]
img_path_third = video_path + '/'+img_lists[2]
img_path_forth = video_path + '/'+img_lists[3]
img_path_fifth = video_path + '/' + img_lists[4]
img_path_sixth = video_path + '/' + img_lists[5]
```

**Comment by kaiwang960112** [comment]
yep，ferplus is a image dataset，as claimed in our paper, we aim to solve the occlusion and large pose problem of FER. Therefore, we crop several region of a face and fed the regions and original face into a CNN

**Comment by kaiwang960112** [comment]
video path is just a variable name.
